version: '2.2'
services:
    Server:
        image: jetbrains/teamcity-server
        volumes:
            - /host_mnt/d/Teamcity/Data:/data/teamcity_server/datadir
            - /host_mnt/d/Teamcity/Logs:/opt/teamcity/logs
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8111:8111
        environment: 
            - TZ=Europe/Amsterdam
        depends_on: 
            - SQL
    SQL:
        image:  mysql:8.0
        volumes: 
            - /host_mnt/d/Teamcity/DB:/var/lib/mysql
        environment: 
            - "MYSQL_USER=teamcity"
            - TZ=Europe/Amsterdam
        env_file:
            - ENV/.ENV_DB
        secrets:
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
    Agent:
        image:  jetbrains/teamcity-agent
        volumes:
            - /host_mnt/d/Teamcity/Agent:/data/teamcity_agent/conf
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - SERVER_URL="192.168.2.100:8111"
secrets:
  MYSQL_PASSWORD:
    file: SECRETS/.DB_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: SECRETS/.DB_ROOT_PASSWORD